dist: xenial

language: php

php:
  - 7.2
  - 7.3
  - 7.4

packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

before_install:
  - mysql -v

script:
  - vendor/bin/phpunit