dist: xenial

language: php

php:
  - 7.2

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - mysql --version
  - mysql -e 'CREATE DATABASE IF NOT EXISTS laravel;'
  - php artisan config:clear
  - php artisan cache:clear
  - php artisan config:cache
  - php artisan migrate:refresh --seed

script:
  - vendor/bin/phpunit --configuration phpunit.xml
  - vendor/bin/phpcs
  - vendor/bin/phpstan analyse

after_success:
  - travis_retry php vendor/bin/php-coveralls
