version: '2'

services:

  nginx:
      image: nginx:latest
      ports:
            - 8083:80
      volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
            - php-box1

  php-box1:
      build: ./docker/php/
      volumes:
            - .:/var/www/html
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      links:
            - database
      environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"

  database:
      image: mysql:5.7
      environment:
            - "MYSQL_ROOT_PASSWORD=common404"
            - "MYSQL_DATABASE=laravel"
      volumes:
            - ./docker/mysql:/var/lib/mysql
            - ./docker/mysqlConfig/log/mysql.log:/var/log/mysql/mysql.log
            - ./docker/mysqlConfig/my.cnf:/etc/mysql/my.cnf
      ports:
            - "33065:3306"
